### ISSUE TITLE
Once instance has previously been poisoned

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustc-perf#136]
The Travis build and a local `cargo test` are failing with:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/rustc_perf-8f74573ec3f5fa9e

running 1 test
test server::serialize_kind ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/rustc_perf-bbd8a26eaced588b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/lib-a6552398a175d66c

running 7 tests
test info ... FAILED
test data_phase ... FAILED
test data_crate ... FAILED
test days ... FAILED
test stats ... FAILED
test summary ... FAILED
test tabular ... FAILED

failures:

---- info stdout ----
	thread 'info' panicked at 'No dates found', /checkout/src/libcore/option.rs:823:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- data_phase stdout ----
	thread 'data_phase' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20

---- data_crate stdout ----
	thread 'data_crate' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20

---- days stdout ----
	thread 'days' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20

---- stats stdout ----
	thread 'stats' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20

---- summary stdout ----
	thread 'summary' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20

---- tabular stdout ----
	thread 'tabular' panicked at 'Once instance has previously been poisoned', /checkout/src/libstd/sync/once.rs:282:20


failures:
    data_crate
    data_phase
    days
    info
    stats
    summary
    tabular

test result: FAILED. 0 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test lib'
```

**Comment by Mark-Simulacrum** [comment]
Yeah, I need to track down the cause. However, it's not affecting the perf.rlo page currently so updates are still possible, if perhaps inadvisable.
