### ISSUE TITLE
"site" fails to start

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/rustc-perf#291]
So I did some benchmarks like the README said and now I want to see the results. I run
```
target/release/site miri-validate
```
matching the `--output-repo miri-validate` I used when benchmarking (the README talks about an `$OUTPUT_DIR`, I can only assume they mean `--output-repo`).

Then I get a panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MutexGuard { lock: Mutex { data: <locked> } }
```
Here's the backtrace... or actually I get two of them, not sure why:
```
stack backtrace:
   0:     0x55a9d978885c - backtrace::backtrace::libunwind::trace::h981d468f18d9bb4b
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hfe5e40c8b7420308
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x55a9d97889e2 - backtrace::capture::Backtrace::new_unresolved::h5e7dacc966731dbd
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x55a9d9676ed8 - failure::backtrace::internal::InternalBacktrace::new::h680dba820e4731c9
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/internal.rs:44
                         - failure::backtrace::Backtrace::new::h6f67b954bddbd056
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/mod.rs:98
   3:     0x55a9d959b738 - <failure::error::Error as core::convert::From<F>>::from::he174a6ead1df5e11
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:34
   4:     0x55a9d95dc755 - site::load::InputData::new::h9c03e372eb3c2fc0
                        at site/src/load.rs:297
   5:     0x55a9d95db9d5 - site::load::InputData::from_fs::h77d6ace302266ad1
                        at site/src/load.rs:263
   6:     0x55a9d953ef41 - site::main::hcdfaae39d673a36e
                        at site/src/main.rs:19
   7:     0x55a9d953f232 - std::rt::lang_start::{{closure}}::h4bcc74b175e6f9c8
                        at /checkout/src/libstd/rt.rs:74
   8:     0x55a9d9884c32 - std::rt::lang_start_internal::{{closure}}::h70046ca1596fed6b
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::he35f788617d92f08
                        at libstd/panicking.rs:310
   9:     0x55a9d98aa0c9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:105
  10:     0x55a9d9887455 - std::panicking::try::h64c03f04c4c5e896
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h1f24a72ce5dffdff
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::h862685159255392f
                        at libstd/rt.rs:58
  11:     0x55a9d953f21f - std::rt::lang_start::hbfc27352b6d160d7
                        at /checkout/src/libstd/rt.rs:74
  12:     0x7f1a1c035b16 - __libc_start_main
  13:     0x55a9d953e739 - _start
  14:                0x0 - <unknown>', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: site::main
             at /checkout/src/libcore/result.rs:782
             at site/src/main.rs:19
  10: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  15: __libc_start_main
  16: _start
```

**Comment by nnethercote** [comment]
@RalfJung: what's the exact benchmarking command(s) you used?

**Comment by RalfJung** [comment]
```
RUST_LOG=info ./target/release/collector --output-repo miri-validate --filter syn  bench_local --builds Opt --rustc ~/.rustup/toolchains/stage2/bin/rustc --cargo `which cargo`  Orig
RUST_LOG=info ./target/release/collector --output-repo miri-validate --filter syn  bench_local --builds Opt --rustc ~/.rustup/toolchains/stage2.2/bin/rustc --cargo `which cargo`  Changed
```
However, now that you mention it, I also did a run where I had a typo in the tag, and then later deleted that json file... but it doesn't seem to keep a list of files it expects somewhere?

**Comment by nnethercote** [comment]
I just ran your commands (with different values for the --rust option, but otherwise identical) and the site started fine with `target/release/site miri-validate`. So I don't know what the problem you're seeing is.

Two output files end up in `miri-validate/times/`:
- `commit-Orig-x86_64-unknown-linux-gnu.json`
- `commit-Changed-x86_64-unknown-linux-gnu.json`

**Comment by nnethercote** [comment]
BTW how much output do you see before the panic? I get the following; I can view the pages once the "Starting server" message is shown.
```
[gulf:~/moz/rustc-perf] target/release/site miri-validate
Updating rust.git clone...
Update of rust.git complete
Starting interpolation...
Interpolation of 0 commits complete in 211.968µs
Starting server with port=2346
```

**Comment by RalfJung** [comment]
Uh, so that's strange. I now tried again and it's working now. I am not aware of doing anything different...
